name: Rust

on:
  release:
    types: [published]
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install additional dependencies
      run: sudo apt install libgl-dev libglu1-mesa-dev libxrandr-dev libxcursor-dev xvfb
    - name: Fetch submodules
      run: git submodule update --init --recursive 
    - name: Build
      run: cargo build --release
    - name: Upload to crates.io
      run: cargo publish --dry-run
